### ISSUE TITLE
Questions about output result

### ISSUE THREAD

**Issue by ouzensang** [ldbc/ldbc_snb_driver#115]
Hi ldbc,
    I am doing some tests based on ladbc_snb. And the graph database provided me their ldbc_snb implementations based on the ldbc_snb_driver. But I am very confused about its output results. There are three questions:
    1. What is the specific meaning of each item in results? I can't find any documents about it. The format of result is like this:
![image](https://user-images.githubusercontent.com/30515579/73353489-65fd0b80-42ce-11ea-9ae4-bba8a97bc6e4.png)
    2. I guess the 'max', 'min', 'mean' items are the processing time of each query, but when I change the number of parameter in file '/ldbc_snb_datagen/substitution_parameters' to 1, the three items still present different values. So if I want to change parameters, if I can just change information in file 'substitution_parameters', or I need to do something else?
    3. I want to know where is the output of each query，like attributes of one person , not just a statistical result of querying many times.

    Thanks very much and I'm looking forward to your early reply!

**Comment by szarnyasg** [comment]
Hi, I'm travelling these days so just a few quick answers:

This doc page might help for interpreting the results (but it's admittedly not very detailed): https://github.com/ldbc/ldbc_snb_driver/wiki/Reading-Benchmark-Results

> I guess the 'max', 'min', 'mean' items are the processing time of each query, but when I change the number of parameter in file '/ldbc_snb_datagen/substitution_parameters' to 1, the three items still present different values.
I don't understand - please clarify.

> So if I want to change parameters, if I can just change information in file 'substitution_parameters', or I need to do something else?
This change should be enough.

> I want to know where is the output of each query，like attributes of one person , not just a statistical result of querying many times.
Query results can be saved by running a 'create validation data' operation
