### ISSUE TITLE
Use multiple threads to execute update operations

### ISSUE THREAD

**Issue by coolerzxw** [ldbc/ldbc_snb_driver#119]
Hi!

I am wondering whether it is possible to use multiple threads to execute update operations in the interactive workload, as I just found that in some cases (e.g. with powerful multi-core servers and efficient storage backends), the serialized execution of update streams would become the bottleneck (i.e. the tested system is far from saturated, but more concurrency of writes is required, otherwise the serialized update operations would eventually violate the schedule time constraints). Generating multiple update streams did not seem to help.

According to the existing audited results on the website, there is a configuration parameter "No. of write streams". I think what I need is something like this, but failed to find related instructions in the current documentation/implementation. 

Thanks!

**Comment by jackwaudby** [comment]
Hi,

It is possible to generate multiple threads of update operations in the driver (emulating users issuing concurrent queries).

The parameter that controls this is `thread-count` in the driver configuration `.properties` file.  

See also issue #62

Jack

**Comment by coolerzxw** [comment]
Hi Jack,

Thanks for your reply. 
It seems that what you mentioned is not related to this issue. I already set many threads (32, 64, and more) for the `thread_count` parameter.
According to the [code](https://github.com/ldbc/ldbc_snb_driver/blob/985b236b643fefeba2b02277fc14a6b62d23885e/src/main/java/com/ldbc/driver/runtime/WorkloadRunner.java#L330), this pool of `thread_count` threads seem to be only responsible for sending complex read and short read requests, not for **updates** (which are handled in [other](https://github.com/ldbc/ldbc_snb_driver/blob/985b236b643fefeba2b02277fc14a6b62d23885e/src/main/java/com/ldbc/driver/runtime/WorkloadRunner.java#L365) threads).
So what I want to achieve is letting the updates to be sent concurrently in multiple client threads, just like these read requests.

Actually, in the reports (Section 3.1) of audited results, there are two parameters regarding the number of threads, one is `No of worker threads` and the other is `No of write streams`.
I think the former can be controlled by `thread_count` in the `.properties` file, but I am not sure how to control the latter.

I understand that this is not easy (according to your response in issue #108 that some updates depend on previous ones), but still want to find potential guidance on sending concurrent updates as otherwise this really limits the throughput.

Xiaowei

**Comment by jackwaudby** [comment]
Can you link me to "(Section 3.1) of audited results" please?

**Comment by szarnyasg** [comment]
@jackwaudby I think @coolerzxw is referring to the [published audits](http://ldbcouncil.org/benchmarks): http://ldbcouncil.org/sites/default/files/LDBC_SNB_I_20150427_SF10_sparksee.pdf#page=7

**Comment by jackwaudby** [comment]
Thanks @szarnyasg 

I've looked into your query @coolerzxw I agree it would be intuitive to have a parameter each for `worker threads` and `write threads` responsible for the reads and writes respectively in the driver's configuration. 

However from what I can gather the number of `write threads` (concurrent update streams) seems to be determined by the number of update partitions outputted by the data generator. 

This is controlled by `ldbc.snb.datagen.serializer.numUpdatePartitions` in the data generator configuration file `params.ini`. If unspecified the default output is 2 streams   `updateStream_0_0_person.csv` `updateStream_0_0_forum.csv` which leads to 2 write threads when the driver executes the workload. E.g.`ldbc.snb.datagen.serializer.numUpdatePartitions:4` _should_ lead to 8 write threads 

Can you try setting `ldbc.snb.datagen.serializer.numUpdatePartitions`, generating some data and then seeing if this then impacts on the number of write threads when you execute the workload?  

Jack

**Comment by coolerzxw** [comment]
Hi @jackwaudby and @szarnyasg ,

Thanks for your help. I had tried using 4 streams but that setting did not seem to help, as these streams appeared to issue updates in an interleave manner. I will try some larger numbers using the `ldbc.snb.datagen.serializer.numUpdatePartitions` parameter and let you know the results.

Xiaowei

**Comment by coolerzxw** [comment]
Hi Jack @jackwaudby ,

I generated 32 streams and now the updates could be issued concurrently across many threads, which should solve the issue. 

Thanks,
Xiaowei
