### ISSUE TITLE
testing the driver with the "simpleworkload"

### ISSUE THREAD

**Issue by dmj2x** [ldbc/ldbc_snb_driver#129]
I don't think this is an issue but I also don't know where else to ask the question.

I am trying to run the test on the ldbc_driver as shown in the read.me file with the following

java \
  -cp target/jeeves-standalone.jar com.ldbc.driver.Client \
  -db com.ldbc.driver.workloads.simple.db.SimpleDb \
  -P target/classes/configuration/simple/simpleworkload.properties \
  -P target/classes/configuration/ldbc_driver_default.properties

However this on returns the printhelpmode usage. I might be missing something especially since this is my first trying it.

Much appreciated!

**Comment by szarnyasg** [comment]
Hi @dmj2x,

This is a good place to ask. What are you trying to accomplish ― is your goal running one of the [reference implementations](https://github.com/ldbc/ldbc_snb_implementations) (e.g. Postgres) or implementing your own client?

Gabor

**Comment by dmj2x** [comment]
Thanks @szarnyasg for getting back to me.

my goal is to compare neo4j and postgres implementations on running the interactive workload. I am in the every early stages trying to set up the environment and run initial test.

**Comment by shinychan95** [comment]
@szarnyasg 

I have same situation that just printing below

"PrintHelpMode  usage: java -cp jeeves-VERSION.jar com.ldbc.driver.Client ... [ ] [ ] ..."

Can I ask how to solve it?

I have tried to
- take different java version 8 and 11.
- take jeeves-0.4.0-SNAPSHOT.jar version, but it has an error (Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger)

**Comment by szarnyasg** [comment]
@dmj2x @shinychan95 you're right, this command was incorrect. I pushed a fix.

**Comment by shinychan95** [comment]
@szarnyasg 

Thank you for replying quickly.

Additionally, I just found the solution that

adding the below dependencies, into `ldbc_snb_driver/pom.xml`

<repository>
    <id>central</id>
    <name>Central Repository</name>
    <url>https://repo.maven.apache.org/maven2</url>
    <layout>default</layout>
    <snapshots>
        <enabled>false</enabled>
    </snapshots>
</repository>

and

<pluginRepository>
    <id>central</id>
    <name>Central Repository</name>
    <url>https://repo.maven.apache.org/maven2</url>
    <layout>default</layout>
    <snapshots>
        <enabled>false</enabled>
    </snapshots>
    <releases>
        <updatePolicy>never</updatePolicy>
    </releases>
</pluginRepository>
       

However, I don't know exactly why it works.
If you can answer right way, please give me answer.


Thank you.
