### ISSUE TITLE
SNB/IW - Parameters ldbc.snb.interactive.LdbcQuery<N>_enable ignored

### ISSUE THREAD

**Issue by whatsthecraic** [ldbc/ldbc_snb_driver#64]
Hi,

I am trying to selectively enable only certain queries from the workload, by setting the entries  in the configuration related to ldbc.snb.interactive.LdbcQuery<N>_enable. For instance:  http://pastebin.com/6cwttJ55 . With this configuration I was expecting that only LdbcQuery2 would be issued, as it is the only entry set with ldbc.snb.interactive.LdbcQuery2_enable = true. 

I verified that indeed the properties are properly parsed by com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcSnbInteractiveWorkload::onInit . Nevertheless all queries continue to be issued, unless when avoiding to register the handlers all together from the driver entry point.

I wonder whether I am misusing this setting or there is some sort of flaw that hinders the driver to recognise the disabled queries?

**Comment by szarnyasg** [comment]
This issue has been resolved since, so I'm closing it.
