### ISSUE TITLE
Driver uses old query parameter filenames.

### ISSUE THREAD

**Issue by jdellithorpe** [ldbc/ldbc_snb_driver#89]
The LDBC data generator was updated a couple months ago to use "interactive" instead of "query" as a prefix for the interactive workload query substitution parameters to distinguish it from the business intelligence workload, however the LDBC driver doesn't appear to have been similarly updated.

**Comment by szarnyasg** [comment]
This was fixed in a87d70339ee42d0060a0fbff517ab9ca152edfc8
